### PR TITLE
We don't need to boot the service provider

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This doesn't work on laravel 5, and we don't need to do it anyway.

### CODE REVIEW

**Comment by ajtrichards** [comment]
Thanks @GrahamCampbell!

**Comment by GrahamCampbell** [comment]
Tests seem to be failing due to an change to laravel rather than this pull.

Ping @etrepat.

**Comment by RomainLanz** [comment]
Ping @etrepat

**Comment by etrepat** [comment]
Sorry for the delay in getting back. I've been very short on spare time lately.

L5 support is now merged in master and 1.1.0 tagged release. 

Thanks.

**Pull request closed without merging**
